### ISSUE TITLE
Re-using revision numbers of failed preprocessing runs breaks

### ISSUE THREAD

**Issue by mikapfl** [pik-piam/madrat#130]
Hi,

We now had two occasions where people had *mysterious* failures in the remind-preprocessing which couldn't be reproduced by me and were generally intractable. In both cases, the runs were re-using a revision number of a previous run and started working when using a fresh revision number. It seems that when a preprocessing fails at a sufficiently inconvenient moment, the cache files are (partly) broken, and when they are re-used, there are all kinds of exciting errors.

I'm not sure what can be done about this, but we should see if this continues to be a problem, and maybe do something about it. Mark revision caches as "not yet ready" when they are created, and only mark them as ready when things actually worked or something.

Cheers

Mika

**Comment by tscheypidi** [comment]
To my knowledge this has not occurred anymore in recent times. I will close this issue, but it can be reopened if the problem shows up again
