### ISSUE TITLE
allow missing years in calcOutput

### ISSUE THREAD

**Issue by fbenke-pik** [pik-piam/madrat#193]
The `calcOutput` function does not support a range of years that includes years not in the data. (https://github.com/pik-piam/madrat/blob/e544b3717fb8d8cbd93ba7c12cc42f333c78c55e/R/calcOutput.R#L300)

For `fullVALIDATIONREMIND` we would like to have the option to pass a year range (e.g. `seq(1970,2050,1)`)  that is applied in every calc function called inside. The year range should just filter for any years within that range and not stop because some of the values are not found in any of the calc function. 

@tscheypidi Is this something we can address directly in `calcOutput`, or should we handle it in `fullVALIDATIONREMIND`? If it can be addressed in `calcOutput`, should it be done via a new parameter or via adjusting the logic for the `years` parameter?

**Comment by tscheypidi** [comment]
One option I see is to convert the error message into a warning and reduce the year filter to the years really available in the data, if there is no full match. Would that solve your problem?

**Comment by fbenke-pik** [comment]
Yes, works for us. Assuming there is no problem with other use cases of calcOutput und backwards-compatibility?

**Comment by tscheypidi** [comment]
given that so far these cases led to an error and in the future would work but create a warning I don't think that there should be any backwards compatibility issues
