### ISSUE TITLE
option zeroWeight=setNA for toolAggregate?

### ISSUE THREAD

**Issue by orichters** [pik-piam/madrat#214]
Example data:
```
  scenario region variable value period   unit  model
1     scen    CAZ       FE     0   2010 US$/EJ REMIND
2     scen    CAZ Price|FE     1   2010 US$/EJ REMIND
3     scen    USA       FE     0   2010 US$/EJ REMIND
4     scen    USA Price|FE     5   2010 US$/EJ REMIND
```
Now, if you run toolAggregate `Price|FE` with `FE` as weight and `zeroWeight = "allow"`, it happily returns 0:
```
library(madrat)
library(magclass)
library(quitte)
library(tidyverse)
d <- data.frame(scenario = "scen", region = c("CAZ", "CAZ", "USA", "USA"), variable = c("FE", "Price|FE"), value = c(0, 1, 0, 5), period = 2010, unit = "US$/EJ", model = "REMIND") %>% as.quitte() %>% as.magpie()
int2ext <- setNames("Price|FE", "FE")

map <- data.frame(region=getRegions(d), world="GLO", stringsAsFactors=FALSE)

toolAggregate(d[,,1], rel = map, weight = d[map$region,,int2ext[1]], zeroWeight = "allow")
```
I wonder whether it would make sense to either just return `NA` for `zeroWeight = allow`, or add a new options `zeroWeight = setNA` which basically set weight2 to `NA` [here](https://github.com/pik-piam/madrat/blob/1289cc63a50b224461535ae2d8ae399d8b4c8756/R/toolAggregate.R#L267) (or just drops the `+ 10^-100`)? This would be useful for price aggregation in remind2, where the World value currently is just set to 0, see https://github.com/pik-piam/remind2/issues/642

Any preference, @tscheypidi?

**Comment by pascal-sauer** [comment]
just returning NA would break a lot of usages, but I don't see a problem with adding a setNA option
